{
  "hash": "acab8ce6225fc15bc7517109adb8959e",
  "result": {
    "engine": "knitr",
    "markdown": "# Equivalence testing {#sec-equivalence}\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n## Motivation\n\nImagine we’re running an experiment comparing **different insect lines or treatments** — for example, testing whether two genetic strains, or two rearing conditions, lead to *different body masses or survival rates*.\n\n### The standard question\n\nTraditionally, we analyze such data using null-hypothesis significance testing (NHST) and design our studies with power analysis.\n\n- The null hypothesis (H₀) says there’s no difference between treatments (e.g., mean body mass difference = 0).\n\n- A significant p-value (p < 0.05) leads us to conclude that there is a difference.\n\n- Power analysis tells us how many samples we need to detect a given difference (e.g., a 5% or 10% change in mass).\n\nThis framework is excellent when our goal is to find differences — for example, when we hope a new treatment improves performance relative to a control.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](equivalence-testing_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### Testing for no difference\n\nIn many biological and applied contexts, the question isn’t “Are they different?” but rather:\n\n> “Are they effectively the same?”\n\nFor example:\n\n- We’ve developed a new insect diet and want to ensure it performs as well as the standard one.\n\n- We’re testing whether two breeding lines have equivalent fitness before merging them in a production colony.\n\n- We want to confirm that a new pesticide formulation is no worse than the established product within a biologically acceptable margin.\n\nIn these cases, a *non-significant* result from a classical test (p > 0.05) does not prove equivalence \n\n> it merely means we don’t have enough evidence to detect a difference.\n\nThe true difference could still be large; we just might not have had enough power.\n\n## Equivalence testing\n\nEquivalence testing inverts the logic:\n\n- We define a Region of Practical Equivalence (ROPE) — a range of differences so small they are biologically or practically negligible (e.g., ±5% in body mass).\n\n- The null hypothesis becomes:\n\n    𝐻0: The true difference lies outside the ROPE (i.e., not equivalent)\n\n\n- The alternative hypothesis:\n\n    𝐻1: The true difference lies entirely within the ROPE (i.e., equivalent)\n\n\nIf the confidence interval for our treatment difference lies completely inside this equivalence range, we can *accept practical equivalence*.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](equivalence-testing_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### What we can do with this\n\nEquivalence testing allows us to:\n\n- Formally conclude that two treatments perform “the same” within a tolerance, rather than merely failing to find a difference.\n\n- Incorporate biological relevance (what counts as a meaningful difference) directly into the statistical test.\n\n- Quantify how much of the observed uncertainty (the CI) lies inside or outside that practical range — via measures like the **Second-Generation p-Value (SGPV)**.\n\n- Design experiments for “sufficient evidence of sameness” (safeguard power or TOST power), not just “evidence of difference.”\n\n## Example:\n\nWe want to know if a new set of diet conditions effects the adult body mass of a set of insects: \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://raw.githubusercontent.com/Philip-Leftwich/Oct-Intro-Analytics/refs/heads/dev/files/body_mass.RDS\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download body mass data as RDS</button>\n</a>\n```\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbody_mass_data <- readRDS(\"body_mass.RDS\")\n\nm_main <- lm(body_mass ~ treatment + sex, data = body_mass_data)\n```\n:::\n\n\n:::{.task}\n::::{.task-header}\nConfidence Intervals\n::::\n::::{.task-container}\n\n- Fit 95% Confidence to your models\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbroom::tidy(m_main, con.fint = T)\n\n#confint(m_main)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |   estimate| std.error|  statistic|   p.value|\n|:-----------|----------:|---------:|----------:|---------:|\n|(Intercept) |  402.79293|  9.185739|  43.849811| 0.0000000|\n|treatmentB  |  -21.81918| 10.606778|  -2.057098| 0.0423608|\n|sexMale     | -202.88252| 10.606778| -19.127629| 0.0000000|\n\n</div>\n:::\n:::\n\n\n\n</div>\n\n\nWe can use our calculated confidence intervals *of the difference* to make a statement about the likely true difference in body mass for insects between treatment A and B.\n\n::::\n:::\n\n## Equivalence testing\n\nIn equivalence testing, we’re not checking whether two means are different, but whether their difference is small enough to be considered practically the same — that is, within some limits (say between −Δ and +Δ).\n\nTo do this, we run two one-sided tests:\n\n- Test if the difference is **greater** than the lower limit (−Δ).\n\n- Test if the difference is **less** than the upper limit (+Δ).\n\nEach of those tests is done at significance level α (for example, α = 0.05).\nFor both conditions to hold, we need **both** one-sided tests to be significant.\n\nNow, when we express this as a single confidence interval, we must account for the fact that we used two one-sided tests — one for each tail. Because α is “spent” on both sides, the combined confidence level becomes (1 – 2α).\n\nSo if α = 0.05, we get a 90% confidence interval, not 95%.\n\n### Set a standard\n\nLet’s say a difference *smaller than 40 g* is acceptable.\n\nThis could be because we think its biologically negligible *or*\n\nit could be that Diet B saves us a lot of money and we are willing to make the tradeoff within certain bounds\n\nFor this data we  define a ROPE (Region of Practical Equivalence) as between 0-40 g weight lost.\n\n\n#### Output example:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(effectsize)\nequivalence_test(m_main, range = c(0,-40))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |Parameter   |  CI|     CI_low|    CI_high|   SGPV| ROPE_low| ROPE_high|ROPE_Equivalence |       p|\n|:--|:-----------|---:|----------:|----------:|------:|--------:|---------:|:----------------|-------:|\n|V1 |(Intercept) | 0.9|  387.53804|  418.04782| 0.0000|        0|       -40|Rejected         | 1.00000|\n|V2 |treatmentB  | 0.9|  -39.43401|   -4.20435| 0.9709|        0|       -40|Accepted         | 1.02118|\n|V3 |sexMale     | 0.9| -220.49735| -185.26768| 0.0000|        0|       -40|Rejected         | 1.00000|\n\n</div>\n:::\n:::\n\n\n#### Interpretation:\n\n- The treatment effect (−21.8 g) lies completely within the ROPE of ±40 g → practically equivalent.\n\n- The sex effect (−203 g) lies far outside the ROPE → meaningful biological difference.\n\n- The **SGPV (Second-Generation p-value)** quantifies how much of the CI overlaps the ROPE (1 = fully inside, 0 = outside).\n\nSo:\n\n- Even though the treatment effect was “statistically significant” (p = 0.04), the equivalence test says it’s practically negligible for our margins.\n\n###  Visualize your equivalence results\n\nYou can use the see package to visualize the CI and ROPE region.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(see)\nplot(equivalence_test(m_main, range = c(0,-40)))\n```\n\n::: {.cell-output-display}\n![](equivalence-testing_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThis shows: \n\n- Each coefficient and its 90% CI\n\n\n<div class='webex-solution'><button>90% CI</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbroom::tidy(m_main, con.fint = T, level = .9)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |   estimate| std.error|  statistic|   p.value|\n|:-----------|----------:|---------:|----------:|---------:|\n|(Intercept) |  402.79293|  9.185739|  43.849811| 0.0000000|\n|treatmentB  |  -21.81918| 10.606778|  -2.057098| 0.0423608|\n|sexMale     | -202.88252| 10.606778| -19.127629| 0.0000000|\n\n</div>\n:::\n:::\n\n\n\n</div>\n\n\n- The ROPE zone (here, ±40 g)\n\n- A colour-coded decision (“Accepted”, “Rejected”, “Undecided”)\n\n:::{.task}\n::::{.task-header}\nTry a different equivalence margin\n::::\n::::{.task-container}\n\n- Are the diets equivalent at 0-20g?\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nequivalence_test(m_main, range = c(0,-20))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |Parameter   |  CI|     CI_low|    CI_high|   SGPV| ROPE_low| ROPE_high|ROPE_Equivalence |        p|\n|:--|:-----------|---:|----------:|----------:|------:|--------:|---------:|:----------------|--------:|\n|V1 |(Intercept) | 0.9|  387.53804|  418.04782| 0.0000|        0|       -20|Rejected         | 1.000000|\n|V2 |treatmentB  | 0.9|  -39.43401|   -4.20435| 0.4122|        0|       -20|Rejected         | 1.021104|\n|V3 |sexMale     | 0.9| -220.49735| -185.26768| 0.0000|        0|       -20|Rejected         | 1.000000|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(equivalence_test(m_main, range = c(0,-20)))\n```\n\n::: {.cell-output-display}\n![](equivalence-testing_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n</div>\n\n\n::::\n:::\n\n## Reporting\n\nA linear model predicting insect body mass revealed a small treatment effect (−21.8 g, 90% CI [−39.4, −4.2]), and a strong effect of sex (−202.9 g, 90% CI [−220.5, −185.3]).\n\nEquivalence testing using a ROPE of ±40g (A 10% difference in mass) indicated that the treatment difference was practically equivalent to zero, whereas the sex difference was meaningful.\n\n\n## Glossary\n\n| **Term**                                   | **Definition**                                                                                                                                                                                                                                  |\n| ------------------------------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |\n| **Null Hypothesis (H₀)**                   | The default assumption that there is *no true difference* between groups or treatments (e.g., mean body mass difference = 0).                                                                                                                   |\n| **Alternative Hypothesis (H₁)**            | The competing claim that there *is* a true difference (e.g., H₁: difference ≠ 0).                                                                                                                                                               |\n| **Region of Practical Equivalence (ROPE)** | A range of effect sizes (e.g., −5% to +5%) considered *biologically or practically negligible*. If the CI of an effect lies entirely within this region, the treatments are deemed practically equivalent.                                      |\n| **Equivalence Testing**                    | A statistical approach that tests whether an observed effect is *small enough* to be considered negligible. Instead of asking “is there a difference?”, it asks “is any difference practically zero?”.                                          |\n| **TOST (Two One-Sided Tests)**             | A frequentist method for equivalence testing that performs two one-sided hypothesis tests—one for each bound of the ROPE—to check whether the effect is significantly greater than the lower bound and smaller than the upper bound.            |\n| **Second-Generation p-Value (SGPV)**       | A measure of how much of the confidence interval lies within the ROPE. Values: 1 → entirely inside (strong evidence for equivalence); 0 → entirely outside (strong evidence against equivalence); between 0–1 → partial overlap (inconclusive). |\n| **Confidence Interval (CI)**               | A range that likely contains the true parameter value with a specified probability (e.g., 90% or 95%). In equivalence testing, the CI is compared directly to the ROPE.                                                                         |\n| **Effect Size**                            | A quantitative measure of the magnitude of a treatment effect (e.g., *Cohen’s d*, *η²*, or regression coefficient). Equivalence testing uses effect size thresholds to define what is “small enough” to be negligible.                          |\n| **Statistical Significance (p-value)**     | The probability of observing an effect as extreme as the current result if H₀ were true. A small p-value (< 0.05) implies evidence against H₀, but does *not* imply equivalence when non-significant.                                           |\n| **Power (1 − β)**                          | The probability that a test correctly rejects a false null hypothesis — i.e., detects a true effect of a specified size. Classic power analysis is designed for detecting differences, not for confirming equivalence.                          |\n| **Practical Equivalence**                  | The conclusion that two treatments perform similarly enough that any difference is negligible for practical or biological purposes.                                                                                                             |\n| **Undecided Region**                       | When the CI overlaps both the ROPE and values outside it, indicating insufficient evidence to conclude either equivalence or difference.                                                                                                        |\n",
    "supporting": [
      "equivalence-testing_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/font-awesome-6.7.2/js/script.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}