{
  "hash": "18193617a04912c5a225c4fe60883477",
  "result": {
    "engine": "knitr",
    "markdown": "# Foundations of Mixed Modelling\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\n\n## Introduction\n\nSo far all of our analyses have dealt with a few explanatory variables - referred to as **fixed effects**. In these examples one of our core assumptions was the **independence** of each data point. That is no two observations are linked, or in any way part of a *subgroup* or *block* effect. \n\nHowever, there are many occasions where this might not be the case:\n\n- We make multiple/repeated measures on a single individual or group of individuals\n\n- We repeat an experiment in different areas or times\n\n- Samples processed in batches (on different days or machines etc.)\n\n- Paired or matched designs\n\nEach of these break the assumption of *independence* in a standard linear model. \n\nSometimes we might know exactly how these blocks of data differ, on other occasions we may have little idea how or why they differ. But when we use a mixed model we can attempt to capture and account for this non-independence. \n\n## What is a mixed model?\n\nMixed models (also known as linear mixed models or hierarchical linear models) are statistical tests that build on the simpler tests of regression, t-tests and ANOVA. All of these tests are special cases of the general linear model; they all fit a straight line to data to explain variance in a systematic way. \n\nThe key difference with a linear mixed-effects model is the inclusion of **random effects** - alongside **fixed effects**.  \n\n\n### Fixed and Random effects\n\n- Fixed effects: are parameters associated with specific, non-random levels of a factor. You estimate a separate coefficient for each level (or contrast) and make inferences about those specific levels. They’re treated as systematic, not varying by chance.\n\nWe can consider this in terms of a very simple linear model, here the estimated intercept is the expected value of the outcome $y$ when the predictor $x$ has a value of 0. The estimated slope is the expected change in $y$ for a single unit change in $x$. These parameters are \"fixed\", meaning that each individual in the population has the same expected value for the intercept and slope. \n\nThe difference between the expected value and true value is called \"residual error\".\n\n$$Y_i = \\beta_0 + \\beta_1X_i + \\epsilon_i$$\n\n- Random effects: are modeled as draws from a probability distribution, typically assumed to be Normal with mean zero and an estimated variance component. Instead of estimating a separate coefficient for each group, the model estimates the variance of the distribution from which those group effects are drawn. You’re not interested in the specific group effects per se, but in how much they vary around a population mean.\n\nThe random effect $U_i$ is often assumed to follow a normal distribution with a mean of zero and a variance estimated during the model fitting process.\n\n$$Y_i = β_0 + U_j + ε_i$$\nDefining what a random effect actually *is* is tricky. The key practical distinction is how they are treated in mixed models.\n\n::: {.callout-note collapse = \"true\"}\n\n## Random effects\n\nIn the book \"Data analysis using regression and multilevel/hierarchical models\" (@gelman_hill_2006). The authors examined five definitions of fixed and random effects and found no consistent agreement. \n\n(1) Fixed effects are constant across individuals, and random effects vary. For example, in a growth study, a model with random intercepts a_i and fixed slope b corresponds to parallel lines for different individuals i, or the model y_it = a_i + b t thus distinguish between fixed and random coefficients.\n\n(2) Effects are fixed if they are interesting in themselves or random if there is interest in the underlying population.\n\n(3) “When a sample exhausts the population, the corresponding variable is fixed; when the sample is a small (i.e., negligible) part of the population the corresponding variable is random.”\n\n(4) “If an effect is assumed to be a realized value of a random variable, it is called a random effect.” \n\n(5) Fixed effects are estimated using least squares (or, more generally, maximum likelihood) and random effects are estimated with shrinkage. \n\nThus it turns out fixed and random effects are not born but made. We must make the decision to treat a variable as fixed or random in a particular analysis. \n:::\n\n\n::: {.callout-warning collapse = \"true\"}\n\n## > 5 levels for random effects\n\nNote that the golden rule is that you generally want your random effect to have at least five levels. So, for instance, if we wanted to control for the effects of fish sex on body length, we would fit sex (a two level factor: male or female) as a fixed, not random, effect.\n\nThis is, put simply, because estimating variance on few data points is very imprecise. Mathematically you could, but you wouldn’t have a lot of confidence in it. If you only have two or three levels, the model will struggle to partition the variance - it will give you an output, but not necessarily one you can trust.\n\nFinally, keep in mind that the name random doesn’t have much to do with mathematical randomness. Yes, it’s confusing. Just think about them as the grouping variables for now. Strictly speaking it’s all about making our models representative of our questions and getting better estimates. Hopefully, our next few examples will help you make sense of how and why they’re used.\n\n There’s no firm rule as to what the minimum number of factor levels should be for random effect and really you can use any factor that has two or more levels. However it is commonly reported that you may want five or more factor levels for a random effect in order to really benefit from what the random effect can do (though some argue for even more, 10 levels). Another case in which you may not want to random effect is when you don’t want your factor levels to inform each other or you don’t assume that your factor levels come from a common distribution. As noted above, male and female is not only a factor with only two levels but oftentimes we want male and female information estimated separately and we’re not necessarily assuming that males and females come from a population of sexes in which there is an infinite number and we’re interested in an average.\n\n:::\n\n\n## Using random effects\n\nSo random effects are usually grouping **factors** for which we are trying to control. *They are always categorical*, as you can’t force R to treat a continuous variable as a random effect. A lot of the time we are not specifically interested in their impact on the response variable, but we know that they might be influencing the patterns we see.\n\nThe mixed-effects model can be used in many situations instead of one of our more straightforward tests when this structure may be important. The main advantages of this approach are: \n\ni) mixed-effects models account for more of the variance \nii) mixed-effects models incorporate group and even individual-level differences\niii) mixed-effects models cope well with missing data, unequal group sizes and repeated measurements\n\n:::{.callout-note}\n## Overdispersion\n\nOne application of mixed models is to account for overdispersion in fixed-dipsersion models (Poisson and Binomial). If a random effect is included to account for individual-level variation we may find our models have a better fit.\n:::\n\n\n## Why use mixed models?\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n### The data\n\nThis dataset represents results from replicate feeding experiments investigating how *Spodoptera frugiperda* larvae respond to increasing concentrations of a plant defensive compound. The explanatory variable is the concentration of the benzoxazinoid DIMBOA incorporated into the larval diet (mM), while the response variable y is a composite detoxification index combining cytochrome P450 and glutathione S-transferase activity together with expression of a marker detoxification gene.\n\nEach group corresponds to an independent experimental replicate—separate batches of larvae reared and assayed under identical conditions on different days—to capture between-replicate variation in baseline activity and toxin responsiveness. \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://github.com/UEABIO/5023B/blob/dev/files/benzo.csv\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download benzoxazinoid data as csv</button>\n</a>\n```\n\n:::\n:::\n\n\n### All in one model\n\nWe will begin by highlighting the importance of considering data structure and hierarchy when building linear models. To illustrate this, we will delve into an example that showcases the consequences of ignoring the underlying data structure. We might naively construct a single linear model that ignores the group-level variation and treats all observations as independent. This oversimplified approach fails to account for the fact that observations within groups are more similar to each other due to shared characteristics.\n\n$$Y_i = \\beta_0 + \\beta_1X_i + \\epsilon_i$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbasic_model <- lm(detox_exp ~ benzo_um, data = benzo_data)\nsummary(basic_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = detox_exp ~ benzo_um, data = benzo_data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-37.23 -12.11  -2.36  11.00  44.53 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  21.0546     1.6490  12.768   <2e-16 ***\nbenzo_um      2.5782     0.2854   9.034   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.96 on 428 degrees of freedom\nMultiple R-squared:  0.1602,\tAdjusted R-squared:  0.1582 \nF-statistic: 81.62 on 1 and 428 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nHere we can see that the basic linear model has produced a statistically significant regression analysis (*t*~428~ = 9.034, *p* <0.001) with an $R^2$ of 0.16. There is a medium effect positive relationship between changes in x and y (Estimate = 2.58, S.E. = 0.29).\n\nWe can see that clearly if we produce a simple plot of x against y: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(benzo_data$benzo_um, benzo_data$detox_exp)\n```\n\n::: {.cell-output-display}\n![Simple scatter plot x against y](mixed-model_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nHere if we use the function `geom_smooth()` on the scatter plot, the plot also includes a fitted regression line obtained using the \"lm\" method. This allows us to examine the overall trend and potential linear association between the variables.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(benzo_data, aes(x = benzo_um, \n                 y = detox_exp)) +\n  geom_point() +\n  labs(x = \"Toxin concentration in diet\", \n       y = \"Detox capacity index\")+\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![Scatter plot displaying the relationship between the independent variable and the dependent variable. The points represent the observed data, while the fitted regression line represents the linear relationship between the variables. The plot helps visualize the trend and potential association between the variables.](mixed-model_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nLooking at the fit of our model we would be tempted to conclude that we have an accurate and robust model.\n\nHowever, when data is hierarchically structured, such as individuals nested within groups, there is typically correlation or similarity among observations within the same group. By not accounting for this clustering effect, estimates derived from a single model can be biased and inefficient. The assumption of independence among observations is violated, leading to incorrect standard errors and inflated significance levels. \n\nFrom the figure below we can see the difference in median and range of x values within each of our groups: \n\n:::{.panel-tabset}\n\n## Differences between groups\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(benzo_data, aes(x = group, \n                 y = detox_exp,\n                 fill = group)) +\n  geom_boxplot() +\n  labs(x = \"Toxin concentration in diet\", \n       y = \"Detox capacity index\")+\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Differences in trends\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Color tagged by group\nplot_group <- ggplot(benzo_data, aes(x = benzo_um, \n                               y = detox_exp, \n                               color = group,\n                               group = group)) +\n  geom_point(alpha = 0.6) +\n  labs(title = \"Data Coloured by Group\", \n       x = \"Toxin concentration in diet\", \n       y = \"Detox capacity index\")+\n  theme(legend.position=\"none\")\n\nplot_group\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\nFrom the above plots, it confirms that our observations from within each of the ranges aren’t independent. We can’t ignore that: as it might make our estimates biased.\n\n### Multiple analyses approach\n\nRunning separate linear models per group, also known as stratified analysis, can be a feasible approach in certain situations. However, there are several drawbacks including\n\n- Increased complexity\n\n- Inability to draw direct conclusions on overall variability \n\n- Reduced statistical power\n\n- Inflated Type 1 error risk\n\n- Inconsistent estimates\n\n- Limited ability to handle unbalanced/missing data\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Plotting the relationship between x and y with group-level smoothing\nggplot(benzo_data, aes(x = benzo_um, y = detox_exp, color = group, group = group)) +\n  geom_point(alpha = 0.6) +  # Scatter plot of x and y with transparency\n  labs(title = \"Data Colored by Group\", x = \"Toxin concentration in diet\", \n       y = \"Detox capacity index\") +\n  theme(legend.position = \"none\") +\n  geom_smooth(method = \"lm\") +  # Group-level linear regression smoothing\n  facet_wrap(~group)  # Faceting the plot by group\n```\n\n::: {.cell-output-display}\n![Scatter plot showing the relationship between the independent variable (x) and the dependent variable (y) colored by group. Each subplot represents a different group. The line represents the group-level linear regression smoothing.](mixed-model_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n<div class='webex-solution'><button>report_p function</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n report_p <- function(p, digits = 3) {\n     reported <- if_else(p < 0.001,\n             \"p < 0.001\",\n             paste(\"p=\", round(p, digits)))\n     \n     return(reported)\n }\n```\n:::\n\n\n\n</div>\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Creating nested benzo_data by grouping the benzo_data by 'group'\nnested_data <- benzo_data |> \n  group_by(group) |> \n  nest()\n\n# Fitting linear regression models to each nested data group\nmodels <- map(nested_data$data, ~ lm(detox_exp ~ benzo_um, data = .)) |>  \n          map(broom::tidy)\n\n# Combining the model results into a single data frame\ncombined_models <- bind_rows(models)\n\n# Filtering the rows to include only the 'x' predictor\nfiltered_models <- combined_models |> \n                   filter(term == \"benzo_um\")\n\n# Adding a column for the group index using rowid_to_column function\ngroup_indexed_models <- filtered_models |> \n                        rowid_to_column(\"group\")\n\n# Modifying the p-values using a custom function report_p\nfinal_models <- group_indexed_models |> \n                mutate(p.value = report_p(p.value))\n\nfinal_models\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| group|term     |   estimate| std.error|  statistic|p.value   |\n|-----:|:--------|----------:|---------:|----------:|:---------|\n|     1|benzo_um |  3.0643940| 0.3620254|  8.4645823|p < 0.001 |\n|     2|benzo_um |  2.5162898| 0.3354848|  7.5004590|p < 0.001 |\n|     3|benzo_um |  1.3904720| 0.3192878|  4.3549169|p < 0.001 |\n|     4|benzo_um |  1.6856649| 0.3550511|  4.7476686|p < 0.001 |\n|     5|benzo_um | -0.0755633| 0.6576868| -0.1148926|p= 0.909  |\n\n</div>\n:::\n:::\n\n> Each analysis has produced a different estimate - and in some cases we did not find a statistically significant association.\n\n### Fixed effects model\n\nUsing a group level term with an effect on x as a fixed effect means explicitly including the terms x and the group as a predictors in the model equation. This approach assumes that the relationship between x and the outcome variable differs across groups and that these differences are constant and fixed. \n\nIt implies that each group has a unique intercept (baseline level) for the relationship between x and the outcome variable. By treating the group level term as a fixed effect, the model estimates *specific parameter values for each group*.\n\n\n$$Y_i = \\beta_0 + \\beta_1X_i + \\beta_2.group_i+\\beta_3(X_i.group_i)+\\epsilon_i$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nadditive_model <- lm(detox_exp ~ benzo_um + group, data = benzo_data)\n\nsummary(additive_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = detox_exp ~ benzo_um + group, data = benzo_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-26.3011  -6.3665  -0.3373   6.6295  31.5816 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  11.7808     1.2931   9.111  < 2e-16 ***\nbenzo_um      2.0242     0.1704  11.883  < 2e-16 ***\ngroup2        3.8771     1.4214   2.728 0.006642 ** \ngroup3       36.3036     1.4286  25.412  < 2e-16 ***\ngroup4        9.2323     1.4215   6.495 2.33e-10 ***\ngroup5        8.0609     2.0922   3.853 0.000135 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.05 on 424 degrees of freedom\nMultiple R-squared:  0.7077,\tAdjusted R-squared:  0.7042 \nF-statistic: 205.3 on 5 and 424 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nIf each group has\n\n- reasonably large sample sizes\n\n- a balanced design (same *n* per group)\n\n- relatively consistent group differences\n\n- when you have few groups (<5)\n\nThen the difference between a fixed-effect model and a mixed-effect model will be *small*. \n\n**BUT**\n\n- When replicate experiments vary in *n*\n\n- When you want to generalise across groups\n\n- When you have lots of groups (> 5 - 10)\n\n- When you have incomplete groups or timepoints\n\nThen mixed models can be much more powerful. \n\n## Our first mixed model\n\nA mixed model is a good choice here: it will allow us to use all the data we have (higher sample size) and account for the correlations between data coming from the groups. We will also estimate fewer parameters and avoid problems with multiple comparisons that we would encounter while using separate regressions.\n\nWe can now join our random effect $U_j$ to the full dataset and define our y values as \n\n$$Y_{ij} = β_0 + β_1*X_{ij} + U_j + ε_{ij}$$.\n\n\nWe have a response variable, and we are attempting to explain part of the variation in test score through fitting an independent variable as a fixed effect. But the response variable has some residual variation (i.e. unexplained variation) associated with group. By using random effects, we are modeling that unexplained variation through variance.\n\nWe now want to know if an association between `y ~ x` exists after controlling for the variation in group.\n\n### Running mixed effects models with lmerTest\n\nThis section will detail how to run mixed models with the `lmer` function in the R package `lmerTest` (@R-lmerTest). This builds on the older `lme4` (@R-lme4) package, and in particular add p-values that were not previously included. There are other R packages that can be used to run mixed-effects models including the `nlme` package (@R-nlme) and the `glmmTMB` package (@R-glmmTMB). Outside of R there are also other packages and software capable of running mixed-effects models, though arguably none is better supported than R software.\n\n\n<div class='webex-solution'><button>Plotting random intercepts</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_function2 <- function(model, data, title = \"Data Coloured by Group\"){\n  \ndata <- data |>  \n  mutate(fit.m = predict(model, re.form = NA),\n         fit.c = predict(model, re.form = NULL))\n\ndata |> \n  ggplot(aes(x = x, y = y, col = group)) +\n  geom_point(pch = 16, alpha = 0.6) +\n  geom_line(aes(y = fit.c, col = group), linewidth = 2)  +\n  coord_cartesian(ylim = c(-40, 100))+\n  labs(title = title, \n       x = \"Independent Variable\", \n       y = \"Dependent Variable\") \n}\n\nmixed_model <- lmer(y ~ x + (1|group), data = data)\n\nplot_function2(mixed_model,benzo_data, \"Random intercept\")\n```\n:::\n\n\n\n</div>\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# random intercept model\nmixed_model <- lmer(detox_exp ~ benzo_um + (1|group), data = benzo_data)\n\nsummary(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: detox_exp ~ benzo_um + (1 | group)\n   Data: benzo_data\n\nREML criterion at convergence: 3224.4\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.61968 -0.63654 -0.03584  0.66113  3.13597 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n group    (Intercept) 205      14.32   \n Residual             101      10.05   \nNumber of obs: 430, groups:  group, 5\n\nFixed effects:\n            Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)  23.2692     6.4818   4.1570    3.59   0.0215 *  \nbenzo_um      2.0271     0.1703 424.0815   11.90   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n         (Intr)\nbenzo_um -0.131\n```\n\n\n:::\n:::\n\n\n\nHere our groups clearly explain a lot of variance \n\n```\n\n205/(205 + 101) = 0.669 / 66.9%\n\n```\n\nSo the differences between groups explain ~67% of the variance that’s “left over” *after* the variance explained by our fixed effects.\n\n\n### Standard Errors\n\nBelow we can take a look at the estimates and standard errors for three of our previously constructed models:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npooled <- basic_model |>  \n  broom::tidy() |>  \n  mutate(Approach = \"Pooled\", .before = 1) |>  \n  select(term, estimate, std.error, Approach)\n\nno_pool <- additive_model |>  \n  broom::tidy() |>  \n  mutate(Approach = \"No Pooling\", .before = 1) |>  \n  select(term, estimate, std.error, Approach)\n\npartial_pool <- mixed_model |>  \n  broom.mixed::tidy() |>  \n  mutate(Approach = \"Mixed Model/Partial Pool\", .before = 1) |>  \n  select(Approach, term, estimate, std.error)\n\nbind_rows(pooled, no_pool, partial_pool) |>  \n  filter(term %in% c(\"x\" , \"(Intercept)\") )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        | estimate| std.error|Approach                 |\n|:-----------|--------:|---------:|:------------------------|\n|(Intercept) | 21.05461|  1.649018|Pooled                   |\n|(Intercept) | 11.78083|  1.293103|No Pooling               |\n|(Intercept) | 23.26919|  6.481821|Mixed Model/Partial Pool |\n\n</div>\n:::\n:::\n\n\nPooling helps to improve the precision of the estimates by borrowing strength from the entire dataset. However, this can also lead to differences in the estimates and standard errors compared to models without pooling. \n\n- Pooled: in the pooled model the averaged estimates may not accurately reflect the true values within each group. As a result, the estimates in pooled models can be biased towards the average behavior across all groups. We can see this in the **too small** standard error of the intercept, underestimating the variance in our dataset. At the same time if there is substantial variability in the relationships between groups, the pooled estimates can be less precise. This increased variability across groups can contribute to larger standard errors of the difference (SED) for fixed effects in pooled models.\n\n- No pooling: This model is extremely precise with the smallest errors, however these estimates reflect conditions only for the **first group in the model**. \n\n- Partial pooling/Mixed models: this model reflects the greater uncertainty of the Mean and SE of the intercept. However, the SED in a partial pooling model accounts for both the variability within groups and the uncertainty between groups. Compared to a no pooling approach, the SED in a partial pooling model tends to be smaller because it incorporates the pooled information, which reduces the overall uncertainty. This adjusted SED provides a more accurate measure of the uncertainty associated with the estimated differences between groups or fixed effects.\n\n## Summary\n\nThe `summary()` function has already provided the estimates of the fixed effects, but they can also be extracted with the `fixef()` function. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfixef(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)    benzo_um \n  23.269187    2.027066 \n```\n\n\n:::\n:::\n\n\nWe can also apply `anova()` to a single model to get an F-test for the fixed effect\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(mixed_model)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|         |   Sum Sq|  Mean Sq| NumDF|    DenDF|  F value| Pr(>F)|\n|:--------|--------:|--------:|-----:|--------:|--------:|------:|\n|benzo_um | 14303.23| 14303.23|     1| 424.0815| 141.6089|      0|\n\n</div>\n:::\n:::\n\n\n\n## Predictions\n\nIt's not always easy/straightforward to make prediciton or confidence intervals from complex general and generalized linear mixed models, luckily there are some excellent R packages that will do this for us. \n\n### `ggpredict`\n\nThe argument `type = random` in the `ggpredict` function (from the ggeffects package @R-ggeffects) is used to specify the type of predictions to be generated in the context of mixed effects models. The main difference between using `ggpredict` with and without `type = random` lies in the type of predictions produced:\n\nWithout `type = random`: `ggpredict` will generate **fixed-effects predictions**. These estimates are based solely on the fixed effects of the model, ignoring any variability associated with the random effects. The resulting estimate represent the average or expected values of the response variable for specific combinations of predictor values, considering only the fixed components of the model.\n\nEstimated mean fixed effects provide a comprehensive view of the average effect of dependent variables on the response variable. By plotting the estimated mean fixed effects using ggpredict, you can visualize how the response variable changes across different levels or values of the predictors while considering the effects of other variables in the model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggeffects)\n\nggpredict(mixed_model, terms = \"benzo_um\") |>  \nplot(x = _, show_data = TRUE)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-20-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nWith `type = random`: ggpredict will generate **predictions** that **incorporate both fixed and random effects**. These predictions take into account the variability introduced by the random effects in the model. The resulting predictions reflect not only the average trend captured by the fixed effects but also the additional variability associated with the random effects at different levels of the grouping factor(s). \n\nBy default the figure now produces **prediction intervals**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(mixed_model, terms = c(\"benzo_um\", \"group\"), type = \"random\") |>  \nplot(x = _, show_data = TRUE)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nFurthermore, `ggpredict()` enables you to explore group-level predictions, which provide a deeper understanding of how the response variable varies across different levels of the grouping variable. By specifying the desired grouping variable in ggpredict when `type = random`, you can generate plots that depict the predicted values for each group separately, allowing for a comparative analysis of group-level effects.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(mixed_model, terms = c(\"benzo_um\", \"group\"), type = \"random\") |>  \nplot(x = _, show_data = TRUE) + \n  facet_wrap(~group)+\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n### `sjPlot`\n\nAnother way to visualise mixed model results is with the package `sjPlot`(@R-sjPlot), and if you are interested in showing the variation among levels of your random effects, you can plot the departure from the overall model estimate for intercepts - *and slopes, if you have a random slope model*:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sjPlot)\n\nplot_model(mixed_model, terms = c(\"benzo_um\", \"group\"), type = \"re\")/\n  (plot_model(mixed_model, terms = c(\"benzo_um\", \"group\"), type = \"est\")+ggtitle(\"Fixed Effects\"))\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-23-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::{.callout-warning}\n\nThe values you see are NOT actual values, but rather the difference between the general intercept or slope value found in your model summary and the estimate for this specific level of random/fixed effect. \n\n:::\n\n\n`sjPlot` is also capable of producing prediction plots in the same way as `ggeffects`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_model(mixed_model,type=\"pred\",\n           terms=c(\"benzo_um\", \"group\"),\n           pred.type=\"re\",\n           show.data = T)+\n  facet_wrap( ~ group)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n### `emmeans`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmeans::emmeans(mixed_model, specs = \"benzo_um\", at = list(x = seq(0,10,2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n benzo_um emmean   SE df lower.CL upper.CL\n     5.02   33.4 6.43  4     15.6     51.3\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n:::\n\n\nIn mixed models, **df are not straightforward because of**:\n\n- The hierarchical structure (e.g., subjects nested in groups),\n\n- Random effects, which reduce the effective number of independent observations.\n\n\n| Method             | What it does                                   | Used by                              |\n| ------------------ | ---------------------------------------------- | ------------------------------------ |\n| **Satterthwaite**  | Estimates df based on uncertainty in SE        | `lmerTest`, `emmeans()`              |\n| **Kenward-Roger**  | More advanced, adjusts SE and df               | `emmeans()`                           |\n| **Asymptotic (∞)** | Assumes large sample, uses normal distribution | `lme4`, `ggpredict()`|\n\n\nWhen df is assumed to be essentially infinite (∞) - we default to the z-distribution, which will produce the narrowest confidence intervals.\n\n\n### Interval types\n\n#### Confidence Intervals:\n\nA confidence interval is used to estimate the range of plausible values for a population parameter, such as the mean or the regression coefficient, based on a sample from that population. It provides a range within which the true population parameter is likely to fall with a certain level of confidence. For example, a 95% confidence interval implies that if we were to repeat the sampling process many times, **95% of the resulting intervals would contain the true population mean**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(mixed_model, terms = \"benzo_um\", interval = \"confidence\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  x| predicted| std.error| conf.low| conf.high|group |\n|--:|---------:|---------:|--------:|---------:|:-----|\n|  0|  23.26919|  6.481821| 10.52885|  36.00952|1     |\n|  2|  27.32332|  6.446136| 14.65313|  39.99351|1     |\n|  4|  31.37745|  6.428332| 18.74225|  44.01265|1     |\n|  6|  35.43158|  6.428560| 22.79594|  48.06722|1     |\n|  8|  39.48571|  6.446816| 26.81418|  52.15724|1     |\n| 10|  43.53984|  6.482949| 30.79729|  56.28239|1     |\n\n</div>\n:::\n:::\n\n\n#### Prediction Intervals:\n\nOn the other hand, a prediction interval is used to estimate the range of plausible values for an individual observation or a future observation from the population. It takes into account both the uncertainty in the estimated model parameters and the inherent variability within the data. A 95% prediction interval provides a range **within which a specific observed or predicted value is likely to fall with a certain level of confidence**. The wider the prediction interval, the greater the uncertainty around the specific value being predicted.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(mixed_model, terms = \"benzo_um\", interval = \"prediction\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  x| predicted| std.error|   conf.low| conf.high|group |\n|--:|---------:|---------:|----------:|---------:|:-----|\n|  0|  23.26919|  11.95906| -0.2369238|  46.77530|1     |\n|  2|  27.32332|  11.93976|  3.8551499|  50.79149|1     |\n|  4|  31.37745|  11.93015|  7.9281549|  54.82674|1     |\n|  6|  35.43158|  11.93028| 11.9820450|  58.88111|1     |\n|  8|  39.48571|  11.94012| 16.0168209|  62.95460|1     |\n| 10|  43.53984|  11.95967| 20.0325298|  67.04715|1     |\n\n</div>\n:::\n:::\n\n\n## Checking model assumptions\n\n### performance\n\nThe `check_model()` function from the performance package in R is a useful tool for evaluating the performance and assumptions of a statistical model, particularly in the context of mixed models. It provides a comprehensive set of diagnostics and visualizations to assess the model's fit, identify potential issues, and verify the assumptions underlying the model, which can be difficult with complex models\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(performance)\ncheck_model(mixed_model,\n            detrend = FALSE)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-28-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### DHARma\n\nSimulation-based methods, like those available with DHARMa (@R-DHARMa), are often preferred for model validation and assumption checking because they offer flexibility and do not rely on specific assumptions. Simulation is particularly useful for evaluating complex models with multiple levels of variability, non-linearity, or complex hierarchical structures. Such models may not be adequately evaluated by solely examining residuals, and simulation provides a more robust approach to assess their assumptions and performance.\n\nRead the authors summary [here](https://theoreticalecology.wordpress.com/2016/08/28/dharma-an-r-package-for-residual-diagnostics-of-glmms/)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(DHARMa)\n\nresid.mm <- simulateResiduals(mixed_model)\n\nplot(resid.mm)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::{.callout-warning}\n\nWhen you have a lot of data, even minimal deviations from the expected distribution will become significant (this is discussed in the help/vignette for the DHARMa package). You will need to assess the distribution and decide if it is important for yourself.\n\n:::\n\n\n\n## Practice Questions\n\n1. In mixed-effects models, independent variables are also called: \n\n<select class='webex-select'><option value='blank'></option><option value=''>Random Effects</option><option value='answer'>Fixed Effects</option><option value=''>Mediators</option><option value=''>Variance</option></select>\n\n2. A random effect is best described as?\n\n<div class='webex-radiogroup' id='radio_PRHHXQIWQU'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_PRHHXQIWQU\" value=\"\"></input> <span>A variable that is noisier than other variables</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_PRHHXQIWQU\" value=\"\"></input> <span>An effect that cannot be predicted based on group membership</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_PRHHXQIWQU\" value=\"answer\"></input> <span>A variable where subgroups influence the outcome</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_PRHHXQIWQU\" value=\"\"></input> <span>Choosing slope values with a random number generator</span></label></div>\n\n\n3. Which of the following is **not** an advantage of mixed-effects models?\n\n<div class='webex-radiogroup' id='radio_BNYXQNZNUE'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BNYXQNZNUE\" value=\"\"></input> <span>They can cope with situations where individuals contribute different numbers of observations</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BNYXQNZNUE\" value=\"\"></input> <span>They can handle group-level differences in the outcome</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BNYXQNZNUE\" value=\"\"></input> <span>They can deal with variation due to different groups</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_BNYXQNZNUE\" value=\"answer\"></input> <span>They are guaranteed to give significant results when ANOVAs do not</span></label></div>\n\n\n4. Mixed-effects models cope well with missing data because?\n\n<div class='webex-radiogroup' id='radio_PAVKEVJWMD'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_PAVKEVJWMD\" value=\"answer\"></input> <span>They can still estimate parameters even when some observations are missing</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_PAVKEVJWMD\" value=\"\"></input> <span>They delete observations with missing data</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_PAVKEVJWMD\" value=\"\"></input> <span>They set all values to 0</span></label></div>\n\n\n\n# Worked Example 1 - Dolphins\n\n\n## How do I decide if it is a fixed or random effect?\n\nOne of the most common questions in mixed-effects modelling is how to decide if an effect should be considered as fixed or random. This can be quite a complicated question, as we have touched upon briefly before the definition of a random effect is not universal. It is a considered process that can include the hypothesis or question you are asking. \n\n1 ) Are you directly interested in the effect in question. If the answer is yes it should be a fixed effect.\n\n2 ) Is the variable continuous? If the answer is yes it should be a fixed effect.\n\n3 ) Does the variable have less than five levels? If ther answer is yes it should be a fixed effect.\n\n\n## Dolphins\n\nThis dataset was collected to measure resting lung function in 32 bottlenose dolphins. The main dependent variable was the tidal volume ($V_T$) measured in litres, as an index of lung capacity. \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://raw.githubusercontent.com/UEABIO/intro-mixed-models/main/book/files/dolphins.csv\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download Dolphins data</button>\n</a>\n```\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndolphins <- read_csv(\"files/dolphins.csv\") \n\ndolphins$direction <- factor(dolphins$direction)\n\ndolphins <- drop_na(dolphins)\n```\n:::\n\n\n\nHere we are interested in the relationship between ($V_T$) and body mass (kg), we have measurements which are taken on the breath *in* and the breath *out*, and each dolphin has been observed between one and four times.\n\nWe need to determine our fixed effects, random effects and model structure:\n\n1) Body Mass <select class='webex-select'><option value='blank'></option><option value=''>Random Effect</option><option value='answer'>Fixed Effect</option></select>\n\n2) Direction <select class='webex-select'><option value='blank'></option><option value=''>Random Effect</option><option value='answer'>Fixed Effect</option></select>\n\n3) Animal 1) Body Mass <select class='webex-select'><option value='blank'></option><option value='answer'>Random Effect</option><option value=''>Fixed Effect</option></select>\n\n4) With the basic structure `y ~ x + z + (1|group)` what do you think this model should be?:\n\n<input class='webex-solveme nospaces' size='20' data-answer='[\"vt ~ bodymass + direction + (1|animal)\",\"vt ~  direction + bodymass + (1|animal)\"]'/>\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n1) We are clearly interested in the effect of body mass on ($V_T$) so this is a **fixed effect**.\n\n2) We may think that the relationship with ($V_T$) and body mass may be different on the in and out breath. We may not be *directly* interested in this, but it has fewer than fivel levels so this is a **fixed effect**. (outbreath coded as 1, inbreath coded as 2).\n\n3) Individual dolphins - if we averaged across measurements for each dolphin, our measurement precision would be different for each animal. If we include each data point, we would be double-counting some animals and our observations would not be independent. To account for the multiple observations we should treat animal as a **random effect**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndolphmod <- lmer(vt ~ bodymass + direction + (1|animal), data=dolphins)\n```\n:::\n\n\n\n</div>\n\n\n\nWith our basic linear model in place - we should carry out model fit checks with `DHARMa` or `performance::check_model()`, but assuming this is a good fit we can look at interpretation:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(dolphmod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: vt ~ bodymass + direction + (1 | animal)\n   Data: dolphins\n\nREML criterion at convergence: 387.4\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.30795 -0.51983  0.04156  0.62404  2.26396 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n animal   (Intercept) 1.039    1.019   \n Residual             1.158    1.076   \nNumber of obs: 112, groups:  animal, 31\n\nFixed effects:\n             Estimate Std. Error        df t value Pr(>|t|)    \n(Intercept)  2.226398   0.627115 28.758081   3.550  0.00135 ** \nbodymass     0.016782   0.003259 26.720390   5.150  2.1e-05 ***\ndirection2   1.114821   0.203389 77.414421   5.481  5.1e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n           (Intr) bdymss\nbodymass   -0.927       \ndirection2 -0.162  0.000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndolphins.1 <- dolphins |>  \n    mutate(fit.m = predict(dolphmod, re.form = NA),\n           fit.c = predict(dolphmod, re.form = NULL))\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndolphins.1 |> \n  ggplot(aes(x = bodymass, y = vt, group = direction)) +\n  geom_point(pch = 16, aes(colour = direction)) +\n  geom_line(aes(y = fit.m, \n                linetype = direction), \n            linewidth = 1)  +\n  labs(x = \"Body Mass\", \n       y = \"VT\") \n```\n\n::: {.cell-output-display}\n![Scatter plot of VT as a function of body mass for dolphins. Different directions of breath are represented by different colors. The solid lines indicate the marginal fitted values from our model.](mixed-model_files/figure-html/unnamed-chunk-35-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_model(dolphmod,type=\"pred\",\n           terms=c(\"bodymass\", \"direction\"),\n           pred.type=\"fe\",\n           show.data = T)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n<div class='webex-solution'><button>A brief summary</button>\n\n\nWe fitted a linear mixed model (estimated using REML and nloptwrap optimizer) to predict ($V_T$) with bodymass(kg) and direction (in/out breath). 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation. We included a random intercept effect of animal to account for repeated measurements (of between 1 to 4 observations) across a total of 32 bottlenosed dolphins. \n\nWe found that for every 1kg increase in bodymass, ($V_T$) increased by 0.02 litres (95% CI [0.01 - 0.02]), . The inbreath had on average a higher volume than the outbreath (1.11 litre difference [0.71 - 1.52]..\n\n**Q.** This is not a perfect write-up, what else could we consider including?\n\n\n</div>\n\n\n\n\n# Multiple random effects\n\nPreviously we used `(1|group)` to fit our random effect. Whatever is on the right side of the `|` operator is a factor and referred to as a “grouping factor” for the term. \n\n### Crossed or Nested\n\nWhen we have more than one possible random effect these can be **crossed** or **nested** - it depends on the relationship between the variables. Let’s have a look.\n\nA common issue that causes confusion is this issue of specifying random effects as either  ‘crossed’ or ‘nested’. In reality, the way you specify your random effects will be determined  by your experimental or sampling design. A simple  example can illustrate the difference. \n\n#### 1. Crossed Random Effects:\n\nCrossed random effects occur when the levels of two or more grouping variables are crossed or independent of each other. In this case, the grouping variables are unrelated, and each combination of levels is represented in the data.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item\" id=\"htmlwidget-06934f421feb80f7a627\" style=\"width:100%;height:480px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-06934f421feb80f7a627\">{\"x\":{\"diagram\":\"\\ndigraph boxes_and_circles {\\n\\n  # a \\\"graph\\\" statement\\n  graph [overlap = true, fontsize = 10]\\n\\n  # several \\\"node\\\" statements\\n  node [shape = box,\\n        fontname = Helvetica]\\n  I; II; 1; 2; 3\\n\\n  # several \\\"edge\\\" statements\\n  I->1 I ->2 I ->3\\n  II ->1  II ->2 II ->3\\n}\\n\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nFully Crossed\n:::\n:::\n\n\n> Example 1: Let's consider a study examining the academic performance of students from different schools and different cities. The grouping variables are \"School\" and \"City\". Each school can be located in multiple cities, and each city can have multiple schools. The random effects of \"School\" and \"City\" are crossed since the levels of these variables are independent of each other.\n\n`lmer(y ~ x + (1 | School) + (1 | City), data = dataset)`\n\n\n> Example 2: Imagine there is a long-term study on breeding success in passerine birds across multiple woodlands, and the researcher returns every year for five  years to carry out measurements. Here  \"Year\" is a  crossed  random  effect with \"Woodland\" as each Woodland can appear in multiple years of study.\nImagine a researcher was interested in understanding  the factors affecting the clutch mass of a passerine bird. They have a study population  spread across five separate woodlands, each containing 30 nest boxes. Every week during  breeding they measure the foraging rate of females at feeders, and measure their  subsequent clutch mass. Some females have multiple clutches in a season and contribute multiple data points. \n\n`lmer(y ~ x + (1 | Year) + (1 | Woodland), data = dataset)`\n\n#### 2. Nested Random Effects:\n\nNested random effects occur when the levels of one grouping variable are completely nested within the levels of another grouping variable. In other words, the levels of one variable are uniquely and exclusively associated with specific levels of another variable.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item\" id=\"htmlwidget-3d9fbd4f8dfbd9f21a72\" style=\"width:100%;height:480px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-3d9fbd4f8dfbd9f21a72\">{\"x\":{\"diagram\":\"\\ndigraph boxes_and_circles {\\n\\n  # a \\\"graph\\\" statement\\n  graph [overlap = true, fontsize = 10]\\n\\n  # several \\\"node\\\" statements\\n  node [shape = box,\\n        fontname = Helvetica]\\n  I; II; 1; 2; 3; 4; 5; 6\\n\\n  # several \\\"edge\\\" statements\\n  I->1 I ->2 I ->3\\n  II ->4  II ->5 II ->6\\n}\\n\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nFully Nested\n:::\n:::\n\n\n> Example 1. Consider a study on the job performance of employees within different departments of an organization. The grouping variables are \"Employee\" and \"Department\". Each employee belongs to one specific department, and no employee can be part of multiple departments. The random effects of \"Employee\" are nested within the random effects of \"Department\" since each employee is uniquely associated with a specific department.\n\n`lmer(y ~ x + (1 | Department/Employee), data = dataset)`\n\n> Example 2: In the same bird study female ID is said to be  nested within woodland : each woodland  contains multiple females unique to that woodland (that never move among woodlands).  The nested random effect controls for the fact that (i) clutches from the same female  are not independent, and (ii) females from the same woodland may have clutch masses  more similar to one another than to females from other woodlands \n\n`lmer(y ~ x + (1 | Woodland/Female ID), data = dataset)`\n\n*or if we remember year we have a model with both crossed and nested random effects*\n\n`lmer(y ~ x + (1 | Woodland/Female ID) + (1|Year), data = dataset)`\n\n\nFor more on designing models around crossed and nested designs check out [this amazing nature paper](https://www.nature.com/articles/nmeth.3137) @krzywinski_2014\n\n\n# Worked Example 2 - Nested design\n\nThis experiment involved a simple one-way anova with 3 treatments given to 6 rats, the researchers the measured glycogen levels in their liver. The analysis was complicated by the fact that three preparations were taken from the liver of each rat, and two readings of glycogen content were taken from each preparation. This generated 6 pseudoreplicates per rat to give a total of 36 readings in all.\n\nClearly, it would be a mistake to analyse these data as if they were a straightforward one-way anova, because that would give us 33 degrees of freedom for error. In fact, since there are only two rats in each treatment, we have only one degree of freedom per treatment, giving a total of 3 d.f. for error.\n\nThe variance is likely to be different at each level of this nested analysis because:\n\nthe readings differ because of variation in the glycogen detection method within each liver sample (measurement error);\nthe pieces of liver may differ because of heterogeneity in the distribution of glycogen within the liver of a single rat;\nthe rats will differ from one another in their glycogen levels because of sex, age, size, genotype, etc.;\nrats allocated different experimental treatments may differ as a result of the fixed effects of treatment.\nIf all we want to test is whether the experimental treatments have affected the glycogen levels, then we are not interested in liver bits within rat’s livers, or in preparations within liver bits. We could combine all the pseudoreplicates together, and analyse the 6 averages. This would have the virtue of showing what a tiny experiment this really was. This latter approach also ignores the nested sources of uncertainties. Instead we will use a linear mixed model.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://raw.githubusercontent.com/UEABIO/intro-mixed-models/main/book/files/rats.rds\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download as rds</button>\n</a>\n```\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrats <- readRDS(\"rats.rds\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrats |>  \n  aggregate(Glycogen ~ Rat + Treatment + Liver, data = _, mean)\n```\n:::\n\n\n```\n   Glycogen Rat Treatment Liver\n1       131   1         1     1\n2       130   1         1     1\n3       131   1         1     2\n4       125   1         1     2\n5       136   1         1     3\n6       142   1         1     3\n7       150   2         1     1\n8       148   2         1     1\n9       140   2         1     2\n10      143   2         1     2\n11      160   2         1     3\n12      150   2         1     3\n13      157   3         2     1\n14      145   3         2     1\n15      154   3         2     2\n16      142   3         2     2\n17      147   3         2     3\n18      153   3         2     3\n19      151   4         2     1\n20      155   4         2     1\n21      147   4         2     2\n22      147   4         2     2\n23      162   4         2     3\n24      152   4         2     3\n25      134   5         3     1\n26      125   5         3     1\n27      138   5         3     2\n28      138   5         3     2\n29      135   5         3     3\n30      136   5         3     3\n31      138   6         3     1\n32      140   6         3     1\n33      139   6         3     2\n34      138   6         3     2\n35      134   6         3     3\n36      127   6         3     3\n\n```\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrats_lmer.1 <- lmer(Glycogen ~ Treatment + (1 | Rat) + (1 | Liver), data = rats)\nsummary(rats_lmer.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Glycogen ~ Treatment + (1 | Rat) + (1 | Liver)\n   Data: rats\n\nREML criterion at convergence: 221.9\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-1.79334 -0.66536  0.01792  0.59281  2.05206 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n Rat      (Intercept) 39.187   6.260   \n Liver    (Intercept)  2.168   1.472   \n Residual             30.766   5.547   \nNumber of obs: 36, groups:  Rat, 6; Liver, 3\n\nFixed effects:\n            Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)  140.500      4.783   3.174  29.373 5.65e-05 ***\nTreatment2    10.500      6.657   3.000   1.577    0.213    \nTreatment3    -5.333      6.657   3.000  -0.801    0.482    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n           (Intr) Trtmn2\nTreatment2 -0.696       \nTreatment3 -0.696  0.500\n```\n\n\n:::\n:::\n\n\n**Q. Why is this model above wrong**\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\nIt is wrong because this would add two random effect terms, one for rat 1 and one for rat 2. In fact there are 6 rats altogether. The way that the data have been coded allows for these kinds of mistakes to happen. The same is true for Liver, which is coded as a 1, 2 or 3. This means that we could write this thinking that we are including the correct random effects for Rat and Liver. In fact, this assumes that the data come from a crossed design, in which there are 2 rats and 3 parts of the liver, and that Liver = 1 corresponds to the same type of measurement in rats 1 and 2 and so on. Sometimes this is appropriate, but not here!\n\nThe nature of the way that many data sets are coded makes these kinds of mistakes very easy to make!\n\n\n</div>\n\n\n\nA better design is the one below:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrats_lmer.2 <- lmer(Glycogen ~ Treatment + (1 | Rat / Liver), data = rats)\nsummary(rats_lmer.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Glycogen ~ Treatment + (1 | Rat/Liver)\n   Data: rats\n\nREML criterion at convergence: 219.6\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-1.48212 -0.47263  0.03062  0.42934  1.82935 \n\nRandom effects:\n Groups    Name        Variance Std.Dev.\n Liver:Rat (Intercept) 14.17    3.764   \n Rat       (Intercept) 36.06    6.005   \n Residual              21.17    4.601   \nNumber of obs: 36, groups:  Liver:Rat, 18; Rat, 6\n\nFixed effects:\n            Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)  140.500      4.707   3.000  29.848 8.26e-05 ***\nTreatment2    10.500      6.657   3.000   1.577    0.213    \nTreatment3    -5.333      6.657   3.000  -0.801    0.482    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n           (Intr) Trtmn2\nTreatment2 -0.707       \nTreatment3 -0.707  0.500\n```\n\n\n:::\n:::\n\n\nAnd we can see the effects in the figures below:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(ggpredict(rats_lmer.2, terms = c(\"Treatment\")))\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-45-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(ggpredict(rats_lmer.2, \n               terms = c(\"Treatment\", \"Rat\"), \n               type = \"random\"), \n     show_data = TRUE)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-46-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n# Reporting Mixed Model Results\n\nOnce you get your model, you have to **present** it in an accurate, clear and attractive form.\n\nThe `summary()` function provides us with some useful numbers such as the amount of variance left over after fitting our fixed effects that can be assigned to each of our random effects. It also provides information on how correlated our random effects are, which may be of interest in understanding the structure of our data as well.\n\nWe can use it to check that the modelled random effect structure matches our data.\n\nIt includes the coefficient estimates, t-statistics and p-values of our fixed effects\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: detox_exp ~ benzo_um + (1 | group)\n   Data: benzo_data\n\nREML criterion at convergence: 3224.4\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.61968 -0.63654 -0.03584  0.66113  3.13597 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n group    (Intercept) 205      14.32   \n Residual             101      10.05   \nNumber of obs: 430, groups:  group, 5\n\nFixed effects:\n            Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)  23.2692     6.4818   4.1570    3.59   0.0215 *  \nbenzo_um      2.0271     0.1703 424.0815   11.90   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n         (Intr)\nbenzo_um -0.131\n```\n\n\n:::\n:::\n\n\n:::{.callout-note}\n\nNote that the t values only appear with df and a p value when using the lmerTest version of lmer(). This is because the degrees of freedom in a mixed-effects model are not well-defined. Often people will treat them as Wald z- values, i.e., as observations from the standard normal distribution. Because the t-distribution asymptotes the standard normal distribution as the number of observations goes to infinity, this \"t-as-z\" practice is legitimate if you have a large enough set of observations.\n\nThe lmerTest function produces estimated degrees of freedom with a satterthwaite approximation (another common method is the \"kenward approximation\"), which will have the effect of widening confidence intervals. It is important to know what method you are using, and to be consistent across your presentation/write-up \n\n:::\n\nWe can also produce an `anova()` type summary of our fixed effects\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(mixed_model)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|         |   Sum Sq|  Mean Sq| NumDF|    DenDF|  F value| Pr(>F)|\n|:--------|--------:|--------:|-----:|--------:|--------:|------:|\n|benzo_um | 14303.23| 14303.23|     1| 424.0815| 141.6089|      0|\n\n</div>\n:::\n:::\n\n\nWe may also wish to report $R^2$ values from our model fit. This requires the `MuMIn` package. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(MuMIn)\nr.squaredGLMM(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            R2m       R2c\n[1,] 0.09949133 0.7027654\n```\n\n\n:::\n:::\n\n\nThis calculates two values the first $R^2_{m}$ is the marginal $R^2$ value, representing the proportion of variance explained by our fixed effects. The second $R^2_{c}$ is the conditional $R^2$, which is the proportion of variance explained by the full model, with both fixed and random effects. \n\n## Tables\n\nThere are a few packages for producing beautiful summary tables from regression models, but not all of them can handle mixed-effects models, the `sjPlot` @R-sjPlot package is one of the most robust and produces a simple HTML table detailing fixed and random effects, produces 95% confidence intervals for fixed effects and calculates those $R^2$ values for you:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsjPlot::tab_model(mixed_model, \n                  df.method = \"satterthwaite\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">detox exp</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">23.27</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">5.54&nbsp;&ndash;&nbsp;41.00</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>0.022</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">benzo um</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">1.69&nbsp;&ndash;&nbsp;2.36</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td colspan=\"4\" style=\"font-weight:bold; text-align:left; padding-top:.8em;\">Random Effects</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&sigma;<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">101.01</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&tau;<sub>00</sub> <sub>group</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">205.00</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">ICC</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.67</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">N <sub>group</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">5</td>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">430</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">Marginal R<sup>2</sup> / Conditional R<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.099 / 0.703</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n## Figures\n\nWe have covered some of the packages that allow us to easily produce marginal and conditional fits, along with 95% confidence or prediction intervals: these will output `ggplot2` figures, allowing plenty of customisation for presentation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Custom colors\n\n\n\nggpredict(mixed_model, terms = c(\"benzo_um\", \"group\" ), \n          type = \"random\") |>  \nplot(x = _, show_data = TRUE) + \n  scale_colour_discrete(palette = \"Dark2\")+\n  scale_fill_discrete(palette = \"Dark2\")+\n  facet_wrap(~group)+theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-51-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n## Write-ups\n\n> We fitted a linear mixed model (estimated using REML) to estimate the effect of \"benzo_um\" on \"detox_exp\". The\nmodel included a random intercept design to allow for the repeated experiment design. The model's total explanatory power is substantial (conditional R^2 = 0.7), and the part related to the fixed effects alone (marginal R2) is 0.099. \nThe effect of x on y was a steady increase of 2.03 per unit of x ([1.69 - 2.36], t(424.1) = 11.9, p < 0.001). \nThese 95% Confidence Intervals (CIs) and p-values were computed using a satterthwaite approximation of the degrees of freedom and a t-distribution approximation.\n\n\n\n# Summary\n\nHere is a suggested workflow:\n\n1. Start with a model containing only fixed effects: Begin by fitting a model with the fixed effects that are relevant to your research question. Include the main predictors and any potential interactions you hypothesize might exist. For example, if you have predictors A and B, you might start with a model like response ~ A + B + A:B.\n\n2. Assess fixed effects and interactions: Evaluate the significance, direction, and magnitude of the fixed effects coefficients. Look for interactions that show significant effects and consider their interpretation in the context of your research question. This step allows you to identify the key variables and interactions that are important in explaining the variation in the response variable.\n\n3. Model evaluation and refinement: Assess the goodness of fit of the fixed effects model using appropriate measures like AIC, BIC, or model deviance. Consider conducting model comparison to evaluate different models with alternative fixed effects structures. This process helps you refine the model and select the most appropriate combination of variables and interactions. *However - this should be no substitution for carefully considered hypotheses and experimental design*. \n\n4. Incorporate random effects: Once you have identified the significant fixed effects and relevant interactions, you can then consider the inclusion of random effects. Random effects capture the variation at different levels and can account for individual differences or clustering within groups. Evaluate the need for random intercepts, random slopes, or crossed random effects based on your research design and the nature of the data.\n\n5. Assess and compare models with random effects: Fit models with random effects and compare their fit to the fixed effects model. Consider appropriate measures such as likelihood ratio tests, AIC, or BIC for model comparison. Evaluate the contribution of the random effects to the model.*However - this should be no substitution for carefully considered hypotheses and experimental design*. And we have seen examples where we leave random effects in place despite LRT tests.\n\n6. Validate and interpret the final model: Validate the final model by assessing assumptions, checking for influential observations, and performing sensitivity analysis. Interpret the estimated coefficients, including fixed effects and random effects, in the context of your research question. Report the results with figures, summary tables and carefully considered text summarising the analysis.\n\nBy initially focusing on the fixed effects, you can establish the foundation of your model and identify the significant predictors and interactions. This step allows you to better understand the relationships in your data and guide the subsequent inclusion of random effects if appropriate.\n\n\n## Mixed Model extensions\n\n\n## Practical problems\n\nBelow are two common issues or warnings you will likely encounter when fitting linear models:\n\n- `boundary (singular) fit: see help('isSingular')`: Your model did fit, but it generated that warning because some of your random effects are very small, common with complex mixed-effect models. You can read more about this in [help page](https://rdrr.io/cran/lme4/man/isSingular.html)\n\n- Convergence warnings: Values for the mixed-effects models are determined using optimisation algorithms. Sometimes these algorithms fail to converge on a best parameter estimate, which will produce an error. There are several possible solutions:\n\n    - Normalise and rescale: Rescaling the variables can mitigate issues caused by the differences in scales or magnitudes of the predictors, which can affect the optimization process. You can rescale the fixed effects predictors by subtracting the mean and dividing by the standard deviation. This centers the variables around zero and scales them to have a standard deviation of 1. This can be done using the scale() function in R.\n    - Try alternative optimisation algorithms:\n    \n    `lmer3 <- lmer(y ~ x + (x | group), data = data, \n    control = lmerControl(optimizer =\"Nelder_Mead\"))`\n    \n    - Finally, although it pains me to admit it, you should try running the model using a different package - each has their own unique and slightly different optimisation protocols. \n\n\n## Further Reading\n\nSome essential reading to continue your mixed-model journey! \n\n- [A brief introduction to mixed effects modelling and multi-model inference in ecology](https://peerj.com/articles/4794/) @xav_2018\n\n- [Mixed Effects Models and Extensions in Ecology with R](https://link.springer.com/book/10.1007/978-0-387-87458-6) @zuur_2009\n\n- [Perils and pitfalls of mixed-effects regression models in biology](https://peerj.com/articles/9522/) @silk_2020\n",
    "supporting": [
      "mixed-model_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/font-awesome-6.7.2/js/script.js\"></script>\n<link href=\"site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"site_libs/viz-1.8.2/viz.js\"></script>\n<link href=\"site_libs/DiagrammeR-styles-0.2/styles.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/grViz-binding-1.0.11/grViz.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}