{
  "hash": "17ff33f5520c195ba15c8e379d19bfd8",
  "result": {
    "engine": "knitr",
    "markdown": "# Linear Models\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Required packages\nlibrary(here)\nlibrary(tidyverse)\nlibrary(GGally)\nlibrary(skimr)\nlibrary(GGally)\nlibrary(ggridges)\nlibrary(performance)\nlibrary(patchwork)\n```\n:::\n\n\n\n## Designing a Model\n\nWe are introduced to the fruitfly dataset (Partridge and Farquhar (1981))[https://nature.com/articles/294580a0]. From our understanding of sexual selection and reproductive biology in fruit flies, we know there is a well established 'cost' to reproduction in terms of reduced longevity for female fruitflies. The data from this experiment is designed to test whether increased sexual activity affects the lifespan of male fruitflies.\n\nThe flies used were an outbred stock, sexual activity was manipulated by supplying males with either new virgin females each day, previously mated females ( Inseminated, so remating rates are lower), or provide no females at all (Control). All groups were otherwise treated identically.\n\n* **type**: type of female companion (virgin, inseminated, control(partners = 0))\n\n* **longevity**: lifespan in days\n\n* **thorax**: length of thorax in micrometres (a proxy for body size)\n\n* **sleep**: percentage of the day spent sleeping\n\n\n### Hypotheses\n\n- Flies paired with non-virgin females do not live as long, they expend more energy trying to mate with previously mated females.\n\n```\n\nlm(longevity ~ type, data = dros_clean)\n\n```\n\n## Checking the data\n\nA quick intro to a general overview\n\nThis is a full two-by-two plot of the entire dataset, but you should try and follow this up with some specific plots. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nGGally::ggpairs(dros_clean)\n```\n\n::: {.cell-output-display}\n![](06-complex-models_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::{.task}\n::::{.task-header}\nYour turn\n::::\n::::{.task-container}\n\n- Make a Boxplot / Density distribution of longevity split by the female type with which males have been paired\n\n::::\n:::\n\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n:::{.panel-tabset}\n\n## Density plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncolours <- c(\"cyan\", \"darkorange\", \"purple\")\n\ndros_clean |> \n  ggplot(aes(x = longevity, y = type, fill = type))+\n  geom_density_ridges(alpha = 0.5)+\n  scale_fill_manual(values = colours)+\n  theme_minimal()+\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](06-complex-models_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## Boxplot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncolours <- c(\"cyan\", \"darkorange\", \"purple\")\n\ndros_clean |> \n  ggplot(aes(x = type, y = longevity, fill = type))+\n  geom_boxplot()+\n  scale_fill_manual(values = colours)+\n  theme_minimal()+\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](06-complex-models_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::\n\n\n</div>\n\n\n## Designing a model\n\nIn this section, we explore how to construct a statistical model to analyse biological data. Specifically, we will build a linear model to examine the effects of mating type on longevity in Drosophila melanogaster. .\n\nUsing the `lm()` function in R, we fit a model to our cleaned dataset, and generate a summary of the results. This approach allows us to assess the significance of each predictor and interpret how these factors influence longevity. By the end of this section, you will understand how to structure a model, choose appropriate variables, and interpret statistical outputs.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# a linear model\nflyls1 <- lm(longevity ~ type, data = dros_clean)\n```\n:::\n\n\n:::{.panel-tabset}\n\n## `summary`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(flyls1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = longevity ~ type, data = dros_clean)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-31.74 -13.74   0.26  11.44  33.26 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       63.560      3.158  20.130  < 2e-16 ***\ntypeInseminated    0.520      3.867   0.134    0.893    \ntypeVirgin       -15.820      3.867  -4.091 7.75e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15.79 on 122 degrees of freedom\nMultiple R-squared:  0.2051,\tAdjusted R-squared:  0.1921 \nF-statistic: 15.74 on 2 and 122 DF,  p-value: 8.305e-07\n```\n\n\n:::\n:::\n\n\n\n## `broom`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbroom::tidy(flyls1)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term            | estimate| std.error|  statistic|   p.value|\n|:---------------|--------:|---------:|----------:|---------:|\n|(Intercept)     |    63.56|  3.157477| 20.1299982| 0.0000000|\n|typeInseminated |     0.52|  3.867103|  0.1344676| 0.8932544|\n|typeVirgin      |   -15.82|  3.867103| -4.0909173| 0.0000775|\n\n</div>\n:::\n:::\n\n\n:::\n\n\n## Interpreting a model\n\n### Call : What model was fitted\n      \n      - `lm(formula = longevity ~ type, data = dros_clean)`\n      \n###  Residuals: How well the model fits\n\n```\n   Min     1Q Median     3Q    Max \n-31.74 -13.74   0.26  11.44  33.26 \n```\n\n### Coefficients: \n\n```\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       63.560      3.158  20.130  < 2e-16 ***\ntypeInseminated    0.520      3.867   0.134    0.893    \ntypeVirgin       -15.820      3.867  -4.091 7.75e-05 ***\n```\n\n| Term                | Interpretation                                                                                          |\n| ------------------- | ------------------------------------------------------------------------------------------------------- |\n| **(Intercept)**     | Mean longevity for the **reference group** (here: *Mated males*, if that’s baseline). → ≈ **63.6 days** |\n| **typeInseminated** | Difference from baseline: ≈ **+0.5 days** (ns, *p* = 0.893)                                             |\n| **typeVirgin**      | Difference from baseline: ≈ **−15.8 days** (**p** < 0.001) → Virgins live ~16 days shorter              |\n\n###  Model fit\n\n```\nResidual SE: 15.79 on 122 DF\nMultiple R-squared: 0.2051\nAdjusted R-squared: 0.1921\nF-statistic: 15.74 on 2 and 122 DF, p-value: 8.31e-07\n```\n\n| Metric          | Meaning                                                                | Interpretation               |\n| --------------- | ---------------------------------------------------------------------- | ---------------------------- |\n| **Residual SE** | Typical deviation of observations from model predictions (≈ 15.8 days) | Smaller = better fit         |\n| **R² = 0.205**  | % of variance in longevity explained by mating type                    | ≈ 20% of variation explained |\n| **Adjusted R²** | Adjusts for # predictors                                               | Still 0.19 → stable          |\n| **F-test**      | “Does `type` matter overall?”                                          | Yes (**p < 0.001**)          |\n\n\n\n## Confidence intervals\n\nWhen we produce a model fit - it is useful to think in terms of *confidence intervals* and estimate differences rather than just p-values. \n\nA 95% confidence interval give us our confidence in having captured the true difference between groups at p = 0.05\n\n\n:::{.panel-tabset}\n\n## Added to model summary\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbroom::tidy(flyls1, conf.int = T)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term            | estimate| std.error|  statistic|   p.value|   conf.low| conf.high|\n|:---------------|--------:|---------:|----------:|---------:|----------:|---------:|\n|(Intercept)     |    63.56|  3.157477| 20.1299982| 0.0000000|  57.309460| 69.810541|\n|typeInseminated |     0.52|  3.867103|  0.1344676| 0.8932544|  -7.135317|  8.175317|\n|typeVirgin      |   -15.82|  3.867103| -4.0909173| 0.0000775| -23.475317| -8.164683|\n\n</div>\n:::\n:::\n\n\n## Visualised\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nGGally::ggcoef_model(flyls1)\n```\n\n::: {.cell-output-display}\n![](06-complex-models_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n\n<div class='webex-solution'><button>Interpretation</button>\n\n\n| Term            | Estimate | 95% CI        | Interpretation                                                                                                                                                                                                |\n| --------------- | -------- | ------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |\n| (Intercept)     | 63.6     | (57.3, 69.8)  | Baseline longevity — flies in the **reference group** (mated males) live about 64 days on average. We are 95% confident the true mean lies between 57 and 70 days.                                            |\n| typeInseminated | 0.52     | (−7.1, 8.2)   | Flies with **inseminated partners** live about 0.5 days longer than the reference group, but the 95% CI spans both negative and positive values — from −7 to +8 days — indicating **no clear difference**.    |\n| typeVirgin      | −15.8    | (−23.5, −8.2) | Flies paired with **virgin partners** live roughly **16 days shorter** on average. The 95% CI (−23.5 to −8.2) does **not include zero**, within our confidence intervals we know that the **true difference** is at least **8.2 days** |\n\n\n\n</div>\n\n\n\n## Add a covariate\n\nIn a basic linear model, we often start by comparing group means — for example:\n\n$$\n\\text{longevity}_i = \\beta_0 + \\beta_1 \\, \\text{type}_i + \\varepsilon_i\n$$\n\nThis model assumes that differences in **longevity are entirely due to type** (e.g., mating partner).\n\nBut in real data, **other variables** may also influence the outcome — for example, body size might affect how long flies live.\n\nIf **mean body size happens to vary slightly between groups**, failing to include it could confound our estimate of the effect of type.\n\nBy adding it as a *covariate*, we adjust for this additional source of variation:\n\n$$\n\\text{longevity}_i = \\beta_0 + \\beta_1 \\, \\text{type}_i + \\beta_2 \\, \\text{thorax}_i + \\varepsilon_i\n$$\n\n### Interpretation\n\n- The coefficient 𝛽1 represents the effect of mating type, after adjusting for body size.\n\n- The coefficient 𝛽2 represents how longevity changes with body size, holding type constant.\n\n- Including covariates often reduces residual variation and improves model fit.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nflyls2 <- lm(longevity ~ type + thorax, data = dros_clean)\n```\n:::\n\n\n\n:::{.task}\n::::{.task-header}\nYour turn\n::::\n::::{.task-container}\n\n* [ ] Fit the updated model\n\n* [ ] What does it say about the effect of body size (thorax) on longevity?\n\n* [ ] What is the adjusted effect of the type on longevity?\n\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(flyls2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = longevity ~ type + thorax, data = dros_clean)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-27.330  -6.803  -2.531   7.143  29.415 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      -56.521     11.149  -5.069 1.45e-06 ***\ntypeInseminated    3.450      2.759   1.250    0.214    \ntypeVirgin       -13.349      2.756  -4.845 3.80e-06 ***\nthorax           143.638     13.064  10.995  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 11.21 on 121 degrees of freedom\nMultiple R-squared:  0.6024,\tAdjusted R-squared:  0.5925 \nF-statistic:  61.1 on 3 and 121 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n</div>\n\n\n\n\n<div class='webex-solution'><button>Mean centering</button>\n\n\nWhen we use continuous predictors, the intercept becomes the expected value of our outcome (longevity), when all predictors are 0. This can make the intercept an unrealistic value. \n\nOne way around this is to \"center\" the continuous predictors - so that 0 now becomes the mean value of the predictor\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndros_clean$thorax_c <- scale(dros_clean$thorax, scale = FALSE)\n\nflyls2_c <- lm(longevity ~ type + thorax_c, data = dros_clean)\n\nsummary(flyls2_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = longevity ~ type + thorax_c, data = dros_clean)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-27.330  -6.803  -2.531   7.143  29.415 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       61.400      2.251  27.277  < 2e-16 ***\ntypeInseminated    3.450      2.759   1.250    0.214    \ntypeVirgin       -13.349      2.756  -4.845  3.8e-06 ***\nthorax_c         143.638     13.064  10.995  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 11.21 on 121 degrees of freedom\nMultiple R-squared:  0.6024,\tAdjusted R-squared:  0.5925 \nF-statistic:  61.1 on 3 and 121 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n</div>\n\n\n::::\n\n:::\n\n## Compare the models\n\nCompare to the simpler model:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(flyls1, flyls2)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|      RSS| Df| Sum of Sq|        F| Pr(>F)|\n|------:|--------:|--:|---------:|--------:|------:|\n|    122| 30407.46| NA|        NA|       NA|     NA|\n|    121| 15210.85|  1|  15196.61| 120.8868|      0|\n\n</div>\n:::\n:::\n\n\nThe ANOVA tests whether adding body_size significantly improves the model.\n\n## Test for interaction\n\nSometimes, the relationship between a covariate and the outcome *differs between groups*.\n\nTo test this, include an interaction term:\n\n$$\n\\text{longevity}_i = \\beta_0 + \\beta_1 \\, \\text{type}_i + \\beta_2 \\, \\text{body\\_size}_i + \\beta_3 \\, (\\text{type}_i \\times \\text{body\\_size}_i) + \\varepsilon_i\n$$\n\nThis allows the **slope of body size to vary by type** — in other words, the effect of size depends on mating partner.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nflyls3 <- lm(longevity ~ type + \n               thorax + \n               type:thorax, # specifies the interaction effect\n             data = dros_clean)\n\nsummary(flyls3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = longevity ~ type + thorax + type:thorax, data = dros_clean)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-27.073  -6.214  -2.487   6.896  29.513 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            -50.2420    22.9821  -2.186   0.0308 *  \ntypeInseminated          0.4241    28.8399   0.015   0.9883    \ntypeVirgin             -26.5521    28.8348  -0.921   0.3590    \nthorax                 136.1268    27.3575   4.976 2.21e-06 ***\ntypeInseminated:thorax   3.5224    34.6547   0.102   0.9192    \ntypeVirgin:thorax       15.9666    34.5973   0.461   0.6453    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 11.29 on 119 degrees of freedom\nMultiple R-squared:  0.6033,\tAdjusted R-squared:  0.5866 \nF-statistic: 36.19 on 5 and 119 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n- A significant interaction (𝛽3) means the relationship between body size and longevity is **not the same** across partner types.\n\nCompare to the simpler model:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(flyls2, flyls3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|      RSS| Df| Sum of Sq|         F|    Pr(>F)|\n|------:|--------:|--:|---------:|---------:|---------:|\n|    121| 15210.85| NA|        NA|        NA|        NA|\n|    119| 15176.42|  2|  34.42543| 0.1349668| 0.8738785|\n\n</div>\n:::\n:::\n\n\nR compares the nested models via a likelihood ratio test (LRT):\n\n- flyls2 = simpler model (without interaction term)\n\n- flyls3 = full model (with interaction term)\n\nThe LRT evaluates:\n\n- H₀: β₃ = 0 (no interaction; same slope for all partner types)\n\n- H₁: β₃ ≠ 0 (interaction; slopes differ)\n\nIf the p-value is small (typically < 0.05), the more complex model explains significantly more variation — implying the interaction is meaningful.\n\n## Model checking\n\nBefore we can interpret the terms in our model, we should check to see if this is even a good way of fitting and measuring our data. We should check the assumptions of our model are being met.\n\nR has ways to do this with the `plot()` function, but the `performance` packages @R-performance from `easystats` also gives nice residual checks:\n\n:::{.panel-tabset}\n\n## base R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Set plotting area to 2x2 (four panels)\npar(mfrow = c(2, 2))\n\n# Plot diagnostic plots\nplot(flyls2)\n```\n\n::: {.cell-output-display}\n![](06-complex-models_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## performance\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_model(flyls2,\n                         detrend = F)\n```\n\n::: {.cell-output-display}\n![](06-complex-models_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n- Posterior Predictive Check – Assesses whether the model’s predicted values align well with the observed data, indicating good model fit.\n\n- Linearity Check – Ensures that the relationship between predictor variables and the outcome is approximately linear, a key assumption of linear regression.\n\n- Homogeneity of Variance Check – Tests whether residuals (errors) have constant variance across all levels of predictors, known as homoscedasticity.\n\n- Influential Observation Check – Identifies individual data points that have a disproportionately large impact on the model’s estimates.\n\n- Collinearity Check – Detects whether predictor variables are highly correlated with each other, which can distort model estimates and reduce interpretability.\n\n- Normality Check – Examines whether the residuals of the model follow a normal distribution, an assumption necessary for reliable inference in linear regression.\n\n### Homogeneity of variance\n\n**Question - IS the assumption of homogeneity of variance met?** <select class='webex-select'><option value='blank'></option><option value='answer'>Yes</option><option value=''>No</option></select>\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n* Mostly - the reference line is fairly flat (there is a slight curve).\n\n* It looks as though there might be some increasing heterogeneity with larger values, though very minor.\n\nVERDICT, pretty much ok, should be fine for making inferences. \n\nWith a slight curvature this could indicate that you *might* get a better fit with a transformation, or perhaps that there is a missing variable that if included in the model would improve the residuals. In this instance I wouldn't be overly concerned. See here for a great explainer on intepreting residuals^[https://www.qualtrics.com/support/stats-iq/analyses/regression-guides/interpreting-residual-plots-improve-regression/].\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Runs a Breusch-Pagan Test for heteroscedasticity\n# Sensitive to outliers, non-normality and sample size\nperformance::check_heteroscedasticity(flyls2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: Error variance appears to be homoscedastic (p = 0.122).\n```\n\n\n:::\n:::\n\n\n\n</div>\n\n\n### Normality of residuals\n\n<select class='webex-select'><option value='blank'></option><option value='answer'>Yes</option><option value=''>No</option></select>\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\nYes - the QQplot looks pretty good, a very minor indication of a right skew, but nothing to worry about. \n\n[Interpreting QQ plots][What is a Quantile-Quantile (QQ) plot?]\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Runs a Shapiro Wilk test of normality\n# Sensitive to outliers, sample size\nperformance::check_normality(flyls2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: residuals appear as normally distributed (p = 0.081).\n```\n\n\n:::\n:::\n\n\n\n</div>\n\n\n\n### Collinearity\n\n**Question - IS their an issue with Collinearity?** <select class='webex-select'><option value='blank'></option><option value=''>Yes</option><option value='answer'>No</option></select>\n\n:::{.callout-tip}\n\nWhat does it mean to have (multi)collinearity?\n\nThis is when one or more predictors are correlated - leading to increased uncertainty about their contributions to the outcome variable. \n\nThe result is wider standard error and confidence intervals. \n\nWhile there are many discussions about what can be done with multicollinearity - I subscribed to the views outlined [here](https://janhove.github.io/posts/2019-09-11-collinearity/). \n\nIt should be reported - but that's it - it represents genuine uncertainty around the contributions of your predictors. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncar::vif(flyls2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           GVIF Df GVIF^(1/(2*Df))\ntype   1.009945  2        1.002477\nthorax 1.009945  1        1.004960\n```\n\n\n:::\n:::\n\n\n:::\n\n## Estimating means and comparisons\n\nUsing the [emmeans](https://aosmith.rbind.io/2019/03/25/getting-started-with-emmeans/) package is a very easy way to produce the estimate mean values (rather than mean differences) for different categories `emmeans`. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmeans <- emmeans::emmeans(flyls2, specs = \n                   ~ type + thorax)\n\nmeans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n type        thorax emmean   SE  df lower.CL upper.CL\n Control      0.821   61.4 2.25 121     56.9     65.9\n Inseminated  0.821   64.8 1.59 121     61.7     68.0\n Virgin       0.821   48.1 1.59 121     44.9     51.2\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nIf the term `pairs()` is included then it will also include post-hoc pairwise comparisons between all levels with a tukey test (adjustment for multiple comparisons) `contrasts`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npairs(means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                                          estimate   SE  df t.ratio\n Control thorax0.82096 - Inseminated thorax0.82096    -3.45 2.76 121  -1.250\n Control thorax0.82096 - Virgin thorax0.82096         13.35 2.76 121   4.845\n Inseminated thorax0.82096 - Virgin thorax0.82096     16.80 2.24 121   7.490\n p.value\n  0.4261\n  <.0001\n  <.0001\n\nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n:::\n\n\n:::{.callout-tip collapse =\"true\"}\n\n## Continuous predictions\n\nFor continuous variables (sleep and thorax) - `emmeans` has set these to the mean value within the dataset, so comparisons are constant between categories at the average value of all continuous variables. If we wish to model continuous predictions we need to specify these:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmeans::emmeans(flyls2, \n                 specs = ~ type + thorax,\n                 at = list(thorax = seq(0.64,0.94, .1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n type        thorax emmean   SE  df lower.CL upper.CL\n Control       0.64   35.4 3.40 121     28.7     42.1\n Inseminated   0.64   38.9 2.79 121     33.3     44.4\n Virgin        0.64   22.1 2.82 121     16.5     27.6\n Control       0.74   49.8 2.57 121     44.7     54.9\n Inseminated   0.74   53.2 1.87 121     49.5     56.9\n Virgin        0.74   36.4 1.89 121     32.7     40.2\n Control       0.84   64.1 2.24 121     59.7     68.6\n Inseminated   0.84   67.6 1.62 121     64.4     70.8\n Virgin        0.84   50.8 1.61 121     47.6     54.0\n Control       0.94   78.5 2.62 121     73.3     83.7\n Inseminated   0.94   81.9 2.27 121     77.5     86.4\n Virgin        0.94   65.1 2.24 121     60.7     69.6\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n:::\n\n## Model reporting\n\nWe have now generated a lot of information from our models - using confidence intervals we can make statements about measured differences and levels of uncertainty around our inferences.\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n- Our control treatment of flies had a mean lifespan of 61.4 days [95%CI: 56.9 - 65.9] at the average thorax size of 0.82mm. \n\n- Thorax size was a significant predictor of longevity (t121 = 10.99, p<0.001), with every additional mm adding a minimum avergae of 11.7 days to lifespan (Estimate = 14.3 [11.7 - 16.9]).\n\n- Treatment (in the form of exposure to different female mating types) had a strong overall effect on longevity (F~1~21~) = 121, p <0.001. Males paired with virgin flies lived an average of 13.3 days [7.9 - 18.8] less than control flies. \n\n- A post-hoc comparison (Tukey HSD) found that males paired with virgin lifes had reduced longevity compared to males paired with both Control and Inseminated females, there was no statisticall significant difference between males paired with Control and Inseminated females. \n\n- Overall the model explained 59% of the observed variance in lifespan (Adjusted R2 = 0.59). \n\n\n\n</div>\n\n\n\n## Causal inference\n\nA regression model can be used for prediction or for causal inference.\n\nIf your goal is to estimate the effect of a variable (e.g., the effect of mating partner on longevity),\nyou must think carefully about which variables to control for and which to exclude.\n\n### Experimental design\n\nYour experimental design is the foundation.\n\n- If you randomly assign treatments (e.g., mating partner type), randomization already balances other factors on average — you don’t need to adjust for everything.\n\n- But for small groups/studies there could be minor imbalances and including the term might help make more precise estimates.\n\n    - If the study is large enough body size differences should smooth out - perhaps it doesn't need to be adjusted for? \n    \n- Body size *could* moderate the treatment effect (change the way mating partner type affects longevity)\n\n- Variables measured **after** treatment (like sleep) should not be adjusted for if they’re potential **mediators**.\n\n    - The type of female a male is paired with might affect how much sleep he gets? \n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/Dag.png){fig-align='center' width=80%}\n:::\n:::\n\nIf we did include sleep in our models it might **block** part of the causal effect of type on longevity that flows *through sleep*. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nflyls4 <- lm(longevity ~ type + thorax + sleep, data = dros_clean)\n\nsummary(flyls4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = longevity ~ type + thorax + sleep, data = dros_clean)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-28.153  -6.836  -2.191   7.196  29.046 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     -56.04502   11.17882  -5.013 1.87e-06 ***\ntypeInseminated   3.62796    2.77122   1.309    0.193    \ntypeVirgin      -13.24603    2.76198  -4.796 4.70e-06 ***\nthorax          144.43008   13.11616  11.012  < 2e-16 ***\nsleep            -0.05281    0.06383  -0.827    0.410    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 11.23 on 120 degrees of freedom\nMultiple R-squared:  0.6046,\tAdjusted R-squared:  0.5914 \nF-statistic: 45.88 on 4 and 120 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nIn this case we can see that the estimate of the effect of type on longevity has *changed*. \n\nOur model now only estimates the effect of type on longevity that isn't *mediated by sleep*. \n\n### Causality terms\n\n| Variable type           | Definition                                                                                                     | Example                                 | Include?               | Why                                                                                                                 |\n| ----------------------- | -------------------------------------------------------------------------------------------------------------- | --------------------------------------- | ---------------------- | ------------------------------------------------------------------------------------------------------------------- |\n| **Confounder**          | A variable that influences both the treatment and the outcome, creating a spurious association.                | (None here; randomization removes them) | ✅                      | Removes bias by blocking non-causal paths between treatment and outcome.                                            |\n| **Mediator**            | A variable that lies on the causal path between treatment and outcome, transmitting part of the effect.        | Sleep                                   | 🚫                     | Excluding it gives the **total effect** of treatment on outcome; including it estimates only the **direct effect**. |\n| **Precision covariate** | A variable related to the outcome but not to treatment; not a confounder but helps explain residual variation. | Thorax                                  | ✅ (optional)           | Improves precision by reducing unexplained variance; doesn’t change the causal estimate.                            |\n| **Moderator**           | A variable that changes (modifies) the strength or direction of the treatment effect.                          | Thorax × Type                           | ✅ (if theory suggests) | Tests whether the effect of treatment depends on another factor (e.g., body size).                                  |\n\n\nChoosing which variables to include in a model requires careful thought because each term represents an assumption about the causal structure of the system. Confounders must be included to remove bias, mediators excluded if we want the total effect, and moderators or precision covariates added only when theory or design supports their relevance. In short, a good model reflects not just the data we have, but the experiment we designed and the biological relationships we believe exist.\n\n\n",
    "supporting": [
      "06-complex-models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}